apiVersion: v1
kind: Service
metadata:
  name: node-js-cluster-service
spec:
  type: NodePort  
  ports:
    - name: server-port
      protocol: "TCP"
      port: 3000
      # Port to forward to inside the pod
      targetPort: 3000
  selector:
    app: node-js-server