apiVersion: v1
kind: Service
metadata:
  name: mongodb-cluster-ip-service
  namespace: nikfilias
spec:
  ports:
      # service port in cluster
    - port: 27017
      # port to contact inside container
      targetPort: 27017
  selector:
    app: mongodb
  type: NodePort