name: node-js-deployment
image: nikfilias/node-js-server
workdir: /src
remote: 2222
forward:
  - 3000:3000
  - 27017:27017
  - 9229:9229
environment:
  - MONGO_URL=0.0.0.0:27017
  - MONGO_USERNAME=adminCluster
  - MONGO_PASSWORD=secret-pass
  - MONGO_DATABASE=users
persistentVolume:
  enabled: true
services:
  - name: mongodb-deployment
    workdir: /app
    image: nikfilias/mongoauth
  - name: mongodb-express

